server:
  port: 8081

# mybatis 的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml               # mybatis配置文件所在路径
  type-aliases-package: com.personal.springcloud.entities          # 所有entities别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml              # mapper映射文件

# spring 的整合
spring:
  application:
   name: microservicecloud-dept     # 该服务对外暴露的服务名，消费者即eureka client客户端 可以通过该名称调用服务提供者   ，消费者集群需要使用同一个服务名，这是实现负载均衡的前提
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
     driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
     url: jdbc:mysql://localhost:3306/clouddb01   #数据库名称
     username: origin
     password: Zlq1993
     dbcp2:
       min-idle: 5    #数据库连接池的最少维持连接数
       initial-size: 5  #初始化连接数
       max-total: 5    #最大连接数
       max-wait-millis: 200    #等待连接获取的最大超时时间

#配置eureka,即服务提供者作为客户端连接到eureka服务端server【注册中心】
eureka:
  client:
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8081-hystrix  #自定义服务名称：后缀加hystrix表示该服务是带熔断器的一个微服务
    prefer-ip-address: true # 访问路径可以显示IP

info:
  app.name: microservicecloud-dept-provider
  company.name: yuanqiang
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}